Fix import tracker for dynamic import
microsoft/TypeScript pull request #41473
Opened 2020-11-10 09:29 UTC by Jack-Works

Fixes #41472

2020-11-11 00:44 UTC, Jack-Works commented
@weswigham would you like to take a look?

2020-11-11 01:25 UTC, Jack-Works commented
![](https://user-images.githubusercontent.com/5390719/98753656-ca253200-23ff-11eb-9a2d-0bb6c4e6ccba.png)

2020-11-25 00:41 UTC, sandersn requested changes
Just some minor suggestions for now. I'll take a real look after Thanksgiving.

2020-11-25 00:41 UTC, sandersn commented on src/services/importTracker.ts
> +        function isExported(node: Node, top: SourceFileLike = node.getSourceFile()) {
You can avoid a double walk up the tree by changing `top` to `stopAtAmbientModule: boolean = false` and `if (node === top)` to `if (stopAtAmbientModule && isAmbientModuleDeclaration(node))`

2020-11-25 00:41 UTC, sandersn commented on src/services/importTracker.ts
> +            else addIndirectUser(top);
I'd recommend refactoring `addIndirectUser`(s) as follows:

1. inline `addIndirectUser` to the top of `addIndirectUsers` and rename the latter to `addIndirectUser`.
2. add a new parameter to `addIndirectUsers`: `addTransitiveDependencies = false`.
2. Change the original first line of `addIndirectUsers` to `if (!isNew || !addTransitiveDependencies) {`
3. In two of the existing uses of `addIndirectUsers`, hard-code the new argument to `true`.
4. In this use, and the other one like it, pass `exported` as the second argument. (`isReexport ...` for the other use

2020-12-02 00:28 UTC, sandersn requested changes
This looks good to me. Just one formatting request since a long 1-line `if` is hard to read (and I thought the linter forbade them entirely?).

2020-12-02 00:28 UTC, sandersn commented on src/services/importTracker.ts
> +                            if (direct.isTypeOf && !direct.qualifier && isExported(direct)) addIndirectUser(direct.getSourceFile(), /** addTransitiveDependencies */ true);
can you break this line (and add braces, I guess)

2020-12-02 22:37 UTC, sandersn approved these changes

2020-12-02 22:46 UTC, merged