No property access from index signature fix
microsoft/TypeScript pull request #41793
Opened 2020-12-03 04:02 UTC by Kingwl

Fixes #41787
Fixes #41786
Fixes #41785

2020-12-03 04:26 UTC, Kingwl commented
I don't know why the tests changes. But seems not my bad?

2020-12-03 17:30 UTC, Kingwl commented
#41803

2020-12-04 02:55 UTC, armanio123 requested changes

2020-12-04 03:20 UTC, Kingwl commented
@orta 
Could @typescript-bot merge master & push automatically?
Or Github has similar features In my memory, but I haven't seen in this repo.

2020-12-04 21:37 UTC, armanio123 approved these changes

2020-12-04 21:37 UTC, merged