fix(43495): noImplicitOverride quick fix puts the keyword in the wrong spot
microsoft/TypeScript pull request #43504
Opened 2021-04-02 18:03 UTC by a-tarasyuk

Fixes #43495

2021-04-02 20:49 UTC, DanielRosenwasser requested changes
Can we also get tests for adding an `override` to a decorated class element?

I assume we don't need a test for `static`, right?

2021-04-02 20:49 UTC, DanielRosenwasser commented on src/services/codefixes/fixOverrideModifier.ts
> +        const accessibilityModifier = find(classElement.modifiers || [], m => isAccessibilityModifier(m.kind));
```suggestion
        const accessibilityModifier = find(classElement.modifiers || emptyArray, m => isAccessibilityModifier(m.kind));
```

2021-04-03 06:40 UTC, a-tarasyuk commented
> Can we also get tests for adding an override to a decorated class element?

I've added several tests for decorated class elements

> I assume we don't need a test for static, right?

I've added a test for this to prove that static members don't have QF

2021-04-03 06:45 UTC, Kingwl commented
Oh thanks!

2021-04-06 19:03 UTC, merged