Ensure static index signatures have an errorNode available
microsoft/TypeScript pull request #44129
Opened 2021-05-17 19:19 UTC by weswigham

So they can actually report the compatibility error they were trying to issue when the string and number index signatures mismatched.

Fixes #44082

2021-05-17 23:08 UTC, DanielRosenwasser requested changes

2021-05-17 23:08 UTC, DanielRosenwasser commented on src/compiler/checker.ts
> +                if (!errorNode) {
Seems like this isn't the right fix - you'll still end up with the wrong error span, just as in the following example:

```ts
class Foo {
  [p: string]: any;
  static [p: string]: number;
}
```

```
error: Property 'prototype' of type 'Foo' is not assignable to string index type 'number'.
```

2021-05-17 23:10 UTC, DanielRosenwasser commented on src/compiler/checker.ts
> +                if (!errorNode) {
I've opened up #44134 to track that.

2021-05-24 21:01 UTC, DanielRosenwasser approved these changes

2021-05-24 21:03 UTC, weswigham commented
@DanielRosenwasser This now fixes both reporting issues and, per our discussion to mitigate the impact of that and preserve the usefulness of the feature, also disables checking if index signatures are consistent with prototype properties on class static sides.

2021-05-24 21:31 UTC, merged

2021-05-24 21:31 UTC, weswigham commented
@DanielRosenwasser you want a cherry pick for this, I assume?

@typescript-bot cherry-pick this into release-4.3