Fix the default text for --useDefineForClassFields
microsoft/TypeScript pull request #45513
Opened 2021-08-19 13:10 UTC by orta

Fixes #45503

2021-08-19 13:30 UTC, MartinJohns commented on src/compiler/diagnosticMessages.json
> +
I don't know how much you care about such things, but this seems to be the only occurrence of an empty newline in this file. One already exists, this PR adds a second.

2021-08-19 21:09 UTC, sandersn requested changes

2021-08-19 21:09 UTC, sandersn commented on src/compiler/diagnosticMessages.json
> +    "`false` unless target is ESNext or above ES2022": {
I'd prefer either

* `true` for ES2022 and above, including ESNext.
* `false` except for ES2022 and above, including ESNext.

and I think it's quite plausible to drop 'including ESNext'.

Also, minor, but: do any other descriptions use backticks? 

I know that no (or few) error messages do, but these descriptions are their own thing.

2021-08-31 21:11 UTC, andrewbranch approved these changes

2021-09-01 14:10 UTC, merged