Improves Date constructor docs in es5.d.ts
microsoft/TypeScript pull request #45520
Opened 2021-08-19 19:56 UTC by bruno-brant

The interface DateConstructor had a number of undocumented formats.
I've added docs to all of them from the descriptio on MDN Date docs, at
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

Fixes #
This PR only improves Date constructor jsdocs for ES5, as per the issue #45519.

2021-08-19 20:06 UTC, MartinJohns commented
As mentioned in #45519, this PR introduces a breaking change by removing the constructor accepting a `number | string` type.

2021-08-19 20:13 UTC, DanielRosenwasser requested changes

2021-08-19 20:13 UTC, DanielRosenwasser commented on src/lib/es5.d.ts
> +     new(value: string): Date;
As mentioned, collapse these into one signature.

2021-08-19 22:51 UTC, RyanCavanaugh commented
I like some of these but not others. The `Integer value representing` phrasing in particular adds a lot of text without commensurately clarifying the parameter and seems like it could just be removed?

2021-09-03 01:02 UTC, sandersn requested changes
Some suggestions for wording. I'm not sure about all of them; let me know what you think.

2021-09-03 01:02 UTC, sandersn commented on src/lib/es5.d.ts
> +      * @param month The month as a number between 0 and 11 (January to December).
these should use mostly the same wording as the constructor above (except for adding "Must be supplied if minutes is supplied.")

2021-09-03 01:02 UTC, sandersn commented on src/lib/es5.d.ts
> +      * Returns the numeric value corresponding to the current time—the number of milliseconds elapsed since January 1,
```suggestion
      * Returns the number of milliseconds elapsed at the current time since January 1, 
```

2022-02-03 19:44 UTC, RyanCavanaugh commented
Housekeeping: Closing due to lack of follow-up. Please open a new PR if you'd like to continue with this. Thanks!

2022-02-03 19:44 UTC, closed without merging