Fix dropped watches
microsoft/TypeScript pull request #47482
Opened 2022-01-17 22:28 UTC by MarcCelani-at

Fixes #47466

On unix systems, fs.watch places a watch on an inode, not a file path. If a given file is assigned a new inode, the watch is no longer valid and any changes to that file will not generate a watch for TypeScript to consume. This is quite common when using standard tools like vim and git.

This changes the watch handling code to always recreate the watch any time a rename event occurs and the file still exists. In this case, it is very likely that the inode changed (at least in my experience), so its a simple solution to the problem and I would guess it has low overhead. This patch eliminates the most common cause of this bug. There are still race conditions after this PR if someone is editing a file in the background at the exact same time that tsc is setting the watch for the first time. To fix that, setting a watch should be done as follows:

1. stat the file
2. create the watch with fs.watch
3. stat the file and make sure that the inode has not changed. If it hasn't, the watch is active.

IMO the TypeScript team should seriously consider just using chokidar. In addition to avoiding bugs like these (both the one fixed here and the one not fixed and described above), it will also provide much better performance on MacOS because it uses the native fsevents system calls.

2022-01-19 05:18 UTC, jakebailey commented
Just to comment on the quote below (and not the PR, which itself seems fine; someone else on the team may be better to review it than me):

> IMO the TypeScript team should seriously consider just using chokidar

FWIW it's unfortunately more complicated than that; `tsc`/`tsserver` make use of a number of different watching methods for different types of files and directories (which makes it difficult to consider switching to something else with different tradeoffs), and adding a third party watcher would introduce a dependency to the typescript package (currently, it has none).

Also of interest may be #43790 (and its linked issues), and that VS Code is actually removing all of its watchers in favor of `@parcel/watcher`.

2022-01-20 23:12 UTC, andrewbranch commented
> I would guess it has low overhead

Have you compared the time between the `git checkout` and the end of `updateGraph` in TS Server logs before and after?

2022-01-21 00:22 UTC, MarcCelani-at commented
I should have been more clear...Re-adding the watch and processing files we are supposed to process comes with cost. We should not expect fixing this bug comes at zero cost.

I think what you are more interested in is what is the overhead of resetting the watch. Setting a watch on every file in our mono repo (over 10k files) takes less than a second, so I don't think we are talking about anything that will have serious performance implications here.

That said, this solution can _potentially_ be optimized by stating the file and checking the inode rather than blindly resetting the watch on every rename event. That's a bit more of a complicated change and I doubt it's worth it given the low cost of setting a watch and that stating the file will introduce new cost as well.

2022-03-24 22:01 UTC, sheetalkamat requested changes
This is incorrect change as this is switching the watcher to "Polling mode" watch instead of relying on file system events which is what it is supposed to do. Polling watch is always going to be accurate but it is CPU intensive and hence less desirable for directories and is only used when there is error.. 
Note that rename event happens whenever a file is added or removed to the folder

If you share your logs, i will be able to investigate the issue and propose the next steps

Eg when watching temp folder, adding file temp/something.js will invoke rename event

2022-03-25 22:20 UTC, MarcCelani-at commented
@sheetalkamat I'm confused by your comment. When I think of poll, I imagine periodically rechecking the state of the file system rather than waiting for a callback from the OS. Here, we are waiting on a callback from the OS, but we are *resetting the watch* when the callback fires because it is very likely to be invalid on Unix OS.

When I use polling on our large monorepo, there is a noticeable overhead to it. I see no measurable overhead to resetting the watch when a file changes.

2022-03-25 22:25 UTC, MarcCelani-at commented
I'm not sure what else I can provide here to help you debug. I detailed a very reliable repro on MacOS in the description. But happy to go over some logs over VC if that will move this forward. We are having to maintain this patch across TS upgrades which is a pain.

2022-03-25 22:36 UTC, MarcCelani-at commented
Also, one final clarification - the rename events occur (at least on macOS) for all sorts of reasons, including when the file changes. It does not only fire for adding/removing a file from the directory.

2022-03-28 17:39 UTC, jakebailey commented
I'm relatively new to the watch code, but I wanted to write out my understanding of the original code and this PR in case it clears things up (so do correct me if I'm wrong).

It seems like `watchPresentFileSystemEntry` will call `fs.watch` and only fall back to `watchPresentFileSystemEntryWithFsWatchFile` when needed. That function is documented in some comments as being based on polling (the function name is super long so I'm just going to call it "the polling watcher" from now on).

The original big long condition in `callbackChangingToMissingFileSystemEntry` is true when the there's a rename event and the file no longer exists, which then leads to the watcher being turned into a polling watcher that waits until an event fires, then recreates the watcher with `watchPresentFileSystemEntry` again.

The PR changes the condition to, on a rename, if it doesn't exist do the same thing as above, but if it does exist, the watcher is recreated assuming that a rename event is likely to mean that the folder points somewhere else on disk via a different inode (as documented in the PR description), but is done so by calling that polling watcher creation function.

That latter point I think is the contentious one; I'd think that if we know (or very likely know) that the watcher is now bad, that it would need to be recreated via `watchPresentFileSystemEntry` in order to have it potentially pick the non-polling watcher again (as it would have originally).

But, it also feels like it _should_ be expensive to be recreating directory watches (which are potentially recursive) over and over again. Maybe that's why the PR uses polling in the first place, because those are effectively "free" given they defer work until some later poll as opposed to asking the system to do some work?

Maybe ideally, it'd be nice if there was a cheap way to just get the inode number of a directory and compare it without doing the work to recreate a watcher (but, this feels like something that node's watcher should really be handling, as the API is based on paths, and it sure would be a surprise for watchers to just totally stop working depending on the details of what some program does to rename or replace a directory/file with other contents or something).

2022-03-28 19:21 UTC, sheetalkamat commented
> The PR changes the condition to, on a rename, if it doesn't exist, do the same thing as above, but if it does exist, the watcher is recreated assuming that a rename event is likely to mean that the folder points somewhere else on disk via a different inode (as documented in the PR description), but is done so by calling that polling watcher creation function.

I think issue here is the number of times the watch will be recreated (if not using polling). Using polling watch on any change in directory is not ideal either. We already have option to allow `watchDirectory` to use Polling https://www.typescriptlang.org/tsconfig#watch-watchDirectory so i don't think this makes optimal change for general use.

I will need to debug and experiment a little to see what better approach will be here.

2022-03-30 23:48 UTC, jakebailey commented
I think that addresses my commentary on the original "it's now going to poll which is wrong" comment, but as mentioned above, recreating a non-polling watcher may get expensive. It'd be worth testing (as it's not a huge change), but I can't claim that's "the thing" that would make the PR correct, compared to some other mechanism to address this problem.

2022-03-30 23:59 UTC, MarcCelani-at commented
Well, given that inode changes require a new watch, I see three possible paths:

1. Depend fully on recursive watches. This is theoretically most scalable and efficient  if it is trustworthy, but we don't seem to trust it on all systems or haven't written the code to do it by default.
2. Stat the file on rename and check for inode changes. If renames typically correspond with inode changes, this stat is only adding more cost.
3. Change the watch on any rename (the intention of this PR). Some watch recreations may be wasteful but we avoid unnecessary file stats.

I'm happy to do either 2 or 3 here.

2022-04-11 19:32 UTC, MarcCelani-at commented
I have completed testing the change to use `watcher = watchPresentFileSystemEntry();`. Interestingly, I have found this to be **more reliable** than the previous commit (contrary to the belief that "Polling watch is always going to be accurate"). I have a very reliable repro in my monorepo that causes incorrect diagnostics with upstream VSCode as well as with `watcher = watchPresentFileSystemEntryWithFsWatchFile();`, but does not repro with `watchPresentFileSystemEntry`. I wonder if the polling watch code is prone to race conditions when files are changing rapidly (as is the case in a git checkout). At any rate, I know @sheetalkamat is still deciding on a long term solution here, but I will update the PR to use `watcher = watchPresentFileSystemEntry()` in case anyone wants to apply this patch to typescript to resolve race conditions.

2022-05-06 19:33 UTC, sheetalkamat commented
Closing in favor of #48997

2022-05-06 19:33 UTC, closed without merging