Instantiation expression can be followed by `let` or `interface` on new line
microsoft/TypeScript pull request #49353
Opened 2022-06-02 14:40 UTC by ahejlsberg

Fixes #49348.

2022-06-02 17:44 UTC, DanielRosenwasser commented on src/compiler/parser.ts
> +                // preceded by a line break, we don't consider them expression starters.
```suggestion
                // Technically strict mode reserved words are valid identifiers in non-strict mode, and can thus
                // start an expression. However, when they follow a type argument list and are immediately
                // preceded by a line break, we don't consider them expression starters.
                // This supports a semicolon-less style for code like the following:
                //
                //   let specialFoo = foo<string>
                //   let value = ...
                //
```

2022-06-02 17:46 UTC, DanielRosenwasser requested changes

2022-06-02 17:46 UTC, DanielRosenwasser commented on src/compiler/parser.ts
> +                case SyntaxKind.LetKeyword:
You need to cover more than just these cases and have tests for them - for example

```ts
class C {
    static specialFoo = f<string>
    static bar = 123;
}

class D {
    public specialFoo = f<string>
    public bar = 123;
}

class E {
    private specialFoo = f<string>
    private bar = 123;
}

class F {
    protected specialFoo = f<string>
    protected bar = 123;
}
```

2022-06-02 17:53 UTC, DanielRosenwasser commented
CC @nicolo-ribaudo @evanw @kdy1 the idea of this PR and issue is that an instantiation expression cannot be followed by a newline and some set of strict-mode reserved words.

2022-06-02 21:06 UTC, nicolo-ribaudo commented
Other than strict-mode keywords, you might also want to special-case `await` (which is only a keyword in modules, and not in general in strict mode).

2022-06-02 21:43 UTC, DanielRosenwasser commented
We just discussed the nuances of `async`. We're considering a rule where if something that could be parsed as an instantiation expression is followed by an identifier or keyword of any sort, then we will favor the instantiation expression (and effectively act as if a user had added a semicolon).

2022-06-02 22:08 UTC, nicolo-ribaudo commented
I hate any new "valid JavaScript has different semantics when parsed as TypeScript" rule, but it's so uncommon to see `a < b > [LineTerminator] c` in JS code that probably no one will never notice it.

2022-06-02 22:27 UTC, DanielRosenwasser commented
> **Maybe OT** Since you are fine-tuning how instantiation expressions are parsed: it's weird that `a<b> ?? c` is not valid code, from a syntactic point of view.

😬

Opened https://github.com/microsoft/TypeScript/issues/49362

2022-06-09 16:19 UTC, sandersn commented
@typescript-bot test top100

2022-06-09 17:18 UTC, sandersn commented
Ran out memory trying to compiler angular ☠️ 
I'm going to try again, especially since I thought angular was part of the user tests too. Maybe it's an old version though.

@typescript-bot test top100

2022-06-09 18:13 UTC, sandersn commented
Let's try again:
@typescript-bot test top100

2022-06-09 20:39 UTC, ahejlsberg commented
@typescript-bot test this
@typescript-bot user test this inline
@typescript-bot run dt
@typescript-bot perf test faster

2022-06-10 14:09 UTC, ahejlsberg commented
All test runs are clean and performance is unaffected.

2022-06-10 16:28 UTC, RyanCavanaugh approved these changes

2022-06-10 17:26 UTC, merged

2022-06-10 20:28 UTC, nicolo-ribaudo commented
Does this PR also change the behavior of new expressions? e.g.
```ts
new A<B>
C
```
does ASI affect this code?

(or as an alternative, it there a playground where I can test it myself? :sweat_smile:)

2022-06-13 13:03 UTC, sosukesuzuki commented
Hi, will this PR be released in the near future?