fix(50224): Intellisense for strings within a type's Union doesn't work properly for JSX
microsoft/TypeScript pull request #50231
Opened 2022-08-09 07:57 UTC by a-tarasyuk

Fixes #50224

2022-08-18 19:11 UTC, sandersn requested changes
The removal of the fallthrough looks wrong to me.

2022-08-18 19:11 UTC, sandersn commented on tests/cases/fourslash/stringLiteralCompletionsInJsxAttributeInitializer.ts
> +////type Props = { a: number } | { b: "b" };
can you change this to something else so it's obvious that the suggestion is the initialiser, not the property name?
```suggestion
////type Props = { a: number } | { b: "somethingelse" };
```

2022-08-18 19:37 UTC, a-tarasyuk commented
Surprisingly, when I re-requested a review from @sandersn, Github removed @gabritto from the reviewers :worried:

2022-08-23 21:58 UTC, sandersn approved these changes

2022-08-23 21:59 UTC, merged