Handle ambient namespace aliasing in getContainersOfSymbol
microsoft/TypeScript pull request #50775
Opened 2022-09-14 18:45 UTC by lauraharker

Fixes #29459

Without this change, the `declNamespaceReexportingLocal.types` would be different - b.ts would print types as `Local` and `_debugger.Foo` instead of `ns.ExportedAlias` and `ns.debugger.Foo`.

2022-10-04 19:37 UTC, DanielRosenwasser commented on tests/baselines/reference/quickInfoDisplayPartsInternalModuleAlias.baseline
> -          "text": "a1",
This corresponds to this line

https://github.com/microsoft/TypeScript/blob/49533168dbb4e19f243b9dbdfd6a3aac69f5b3dd/tests/cases/fourslash/quickInfoDisplayPartsInternalModuleAlias.ts#L8

which seems like - I don't know, it feels like a regression that this doesn't display `a1` at all anymore.

2022-11-07 21:25 UTC, weswigham requested changes
This probably works, but definitely needs some perf results, since it expands the container search space pretty significantly. Putting the `candidates` into a `Set` or calling `deduplicate` on the candidates list could be pretty useful, too. (Plus that test updated to actually have declarations on).

2022-11-30 22:50 UTC, lauraharker commented on tests/cases/compiler/declNamespaceReexportingLocal.ts
> +// @Filename: /a.d.ts
Done

2022-11-30 22:50 UTC, lauraharker commented
@weswigham I've deduplicated the candidates list. Would you have any suggested projects for performance tracing?

Most of the TS projects I work on are Google internal and the process we have for patching Google's internal TS compiler binary is quite involved - I'd like to avoid it if possible :)

2023-03-10 18:00 UTC, jakebailey commented
The perf result here looks bad but it could be because the PR is old and contains conflicts, so might be testing without a bunch of changes from main.

2023-03-10 18:11 UTC, jakebailey commented
I went and merged main.

@typescript-bot perf test this

2023-03-10 22:41 UTC, jakebailey commented
There we go, that seems much more reasonable.

2026-03-24 21:17 UTC, closed without merging