Cover more cases for node module packageRootPath Auto-import
microsoft/TypeScript pull request #54024
Opened 2023-04-26 03:22 UTC by hanzooo

Fixes https://github.com/microsoft/TypeScript/issues/54023

2023-04-27 04:11 UTC, hanzooo commented
> This PR doesn't have any linked issues. Please open an issue that references this PR. From there we can discuss and prioritise.

@typescript-bot check it again？

2023-05-04 00:06 UTC, andrewbranch requested changes
This is close, but needs a couple more conditions. This behavior is deprecated for packages with `"type": "module"`:

<img width="683" alt="image" src="https://user-images.githubusercontent.com/3277153/236076338-ed82a1d0-b60f-4d4d-bf03-041986c63d9d.png">

And TypeScript module resolution doesn’t support it. So we can’t do this if the package has `"type": "module"`.

Secondly, we need to make sure that the extension on `index.{???}` is something that supports omitting the extension. E.g., if the file is `index.mjs` or `index.d.cts`, those cannot be resolved by a directory reference.

2023-05-04 17:03 UTC, hanzooo commented
> 

@andrewbranch Thx for the review, and detailed feedback~ I just added more checks for this.

2023-05-08 16:38 UTC, andrewbranch commented on src/compiler/moduleSpecifiers.ts
> +                    !fileExtensionIsOneOf(canonicalModuleFileToTry, [Extension.Mjs, Extension.Cjs, Extension.Dmts, Extension.Dcts]) &&
```suggestion
                    !fileExtensionIsOneOf(canonicalModuleFileToTry, extensionsNotSupportingExtensionlessResolution) &&
```

(needs import too)

2023-05-09 16:46 UTC, andrewbranch approved these changes
Thank you!

2023-05-09 16:46 UTC, merged