Error on export default of type: issue https://github.com/microsoft/TypeScript/issues/55087
microsoft/TypeScript pull request #55097
Opened 2023-07-21 03:29 UTC by EliLichtblau

This changes the behavior of TS to the specified behavior in [issue](https://github.com/microsoft/TypeScript/issues/55087).

Export default of types become errors - i.e
```ts
type foo = 3
export default foo
```
This is because if it does not error - typescript emits invalid code.

2023-07-21 03:31 UTC, EliLichtblau commented
@microsoft-github-policy-service agree

2023-07-21 03:36 UTC, EliLichtblau commented
Fixes: [#55087](https://github.com/microsoft/TypeScript/issues/55087)

- trying to trigger link issue

2023-07-21 16:04 UTC, fatcerberus commented
FWIW I think it's okay to default-export types in general, as long as they *only* have a typespace meaning--the problem is when you default-export something that has a valuespace meaning (like a class) which has been imported via `import type`.

2023-07-23 05:03 UTC, EliLichtblau commented
If this is the only condition - I think you can just convert 
```ts
 if (!isIllegalExportDefaultInCJS && !(node.flags & NodeFlags.Ambient) && compilerOptions.verbatimModuleSyntax && getTypeOnlyAliasDeclaration(sym, SymbolFlags.Value)) {
```
to 
```ts
if (!(node.flags & NodeFlags.Ambient) && getTypeOnlyAliasDeclaration(sym, SymbolFlags.Value)) {
```

the reason I find this a little awkward is checking with ts-fork-typechecker but emitting with ts loader transpileOnly is pretty common and you can pass the typechecking stage and still emit invalid code as the following code:
```ts
ts.transpileModule(`
import {type Node} from "typescript"
export default Node
`, {})
```
will give you
```ts
export default Node
```
even though Node is an interface. I can understand why you (the TS team) would say this is improper use and shouldn't be supported though.

With that said, my take is: 
* There should be a flag which disables all export default of things (need a better word here sorry) imported in a typeOnly context as this can emit invalid code with transpileModule calls
* The check on export default of import types should not live behind the verbatim module syntax flag and should be default behavior 


But I will implement whatever you think is best

The best solution IMO is to not change compile time behavior at all and for emit to just work but based on your comments in the issue I am unsure if this is possible. I know less than little about the emit phase so I don't have any idea here.

2023-08-05 00:22 UTC, andrewbranch requested changes
I think the expected behavior is

- an `export default` of a type-only import never emits anything
- it’s an error only in `isolatedModule` (ts1205)

2023-11-13 20:28 UTC, andrewbranch commented
Fixed the checker behavior, still need to fix the emit

2023-11-13 20:48 UTC, andrewbranch commented
Ok, ready.

2023-11-13 20:56 UTC, jakebailey approved these changes
LGTM but should get the extended test run.

2023-11-13 20:56 UTC, jakebailey commented on tests/baselines/reference/exportDefault.js
> -exports.default = types;
Oops!

2023-11-13 20:56 UTC, jakebailey commented
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot run dt

@typescript-bot perf test this

2023-11-13 21:39 UTC, andrewbranch commented on tests/baselines/reference/exportDefault.js
> -exports.default = types;
Yeppp

2023-11-17 21:37 UTC, andrewbranch commented
These errors from the top repos look possibly wrong, especially the playwright one. Need to take a closer look.

2023-11-17 21:51 UTC, andrewbranch commented
@typescript-bot test top200

2023-11-17 22:02 UTC, jakebailey commented
You can ignore that playwright one, that is currently happening on every PR and we just haven't looked at why.

2023-11-17 22:05 UTC, andrewbranch commented
Huh? The playwright one is clearly caused by this and fixed in the latest commit.

2023-11-17 22:07 UTC, jakebailey commented
Apologies, I mixed up the "P" libraries and confused playwright for puppeteer (which you can see on other PRs like https://github.com/microsoft/TypeScript/pull/56429#issuecomment-1814887414). Ignore me!

2023-11-20 18:19 UTC, merged