Parse reserved identifiers as dotted names of ambient modules
microsoft/TypeScript pull request #55282
Opened 2023-08-06 08:28 UTC by Andarist

fixes https://github.com/microsoft/TypeScript/issues/7840

2023-08-24 15:23 UTC, sandersn requested changes
Do we really need this fix? Namespaces are rarely written these days -- they're still automatically generated but I don't think this fix will make a difference there. And there's a well-understood workaround available.

2023-08-24 16:44 UTC, jakebailey commented
Honestly, I don't mind fixing it; esbuild gets this right: https://jakebailey.dev/esbuild-playground/#v3=PTAEAEDMEsBsFMB2BDAtvAXKAxge0TAOYB0AVgM74BQA3laKAERIAuATgJ4AKu0iL5RlgDajYHwAm8AB7EB0xgF0ANPSaRcbVMhZCm8cqkZUAvlSogIMBCnRZJMueWlUp2WMjbxQqXBICuCDgAFmy46MRSAEb+hITwbKB0DAxuHl6gAG6eoCzIUQCSEliI-qhRCQDcpuYyAA6aLDj45E15hRKgALwhYRHRsfFscvlF1a7w7p7evgFBLAYsxFPk5ElmE1MZs4HeA3EJ66CWrXCwoMiIoAlhbEA

2023-08-24 16:50 UTC, Andarist commented on tests/baselines/reference/ambientModuleDeclarationWithReservedIdentifierInDottedPath.errors.txt
> +    declare module chrome.debugger {
While the syntax is supported - shouldn't I add extra tests with `declare namespace` instead of changing this one?

2023-08-28 21:46 UTC, sandersn approved these changes

2023-08-28 21:48 UTC, merged