Use `...args: never` in builtin conditional type helpers
microsoft/TypeScript pull request #55714
Opened 2023-09-11 19:08 UTC by Andarist

closes https://github.com/microsoft/TypeScript/issues/55667 , cc @andrewbranch

2023-09-11 19:17 UTC, jakebailey commented
@typescript-bot test top200
@typescript-bot user test this
@typescript-bot run dt
@typescript-bot perf test this
@typescript-bot pack this

2023-09-11 21:10 UTC, DanielRosenwasser commented
Why not `InstanceType`?

2023-09-11 21:14 UTC, andrewbranch commented on src/lib/es5.d.ts
Should `InstanceType` have been updated in this file?

2023-09-11 21:29 UTC, Andarist commented
I missed the `InstanceType` with my multi-cursor edit :v thanks for catching that.

2023-09-11 21:32 UTC, andrewbranch commented
@typescript-bot user test this
@typescript-bot test top200

2023-09-12 07:27 UTC, Andarist commented
Extracted (not exactly minimal yet) repro from `vuetify`: [TS playground](https://www.typescriptlang.org/play?ts=5.2.2#code/C4TwDgpgBAkgZgQQHYgDwBUA0UCa2ByAfFALxQAMUEAHsBEgCYDOUAjFAGRTpQD8uUAFxR8AbgBQoSFAAiAQ2BzSUAEoQAxgHsATg1RNg2gJZIA5tgCuSANZJNAdySEJU6DIhw5FgDbAAYnLqwDpo6MRkABRg2ppgTMLyigCUpMQ8AD5QSD7eUJlWDB4mEAwu4NAAwpoAtmCaSPTAAPIARgBWGsAACjFxTWDARvVMqF3KiXLhUADe4lBQANoA0lAmUNYQIJpwUF0AusI9saPLe8SZ2d7eEgC+EiZ02p7q0Edg-YPDGMpyKNgyyjCMzmUFcvEOvXQ5Qw51B2gs0AuOQk820EAAjhYjGiGOCoC1NJpvBBfiioIVPD5gHiAZl3JTfAEgiFUDJYZdcvlGEUGgw8lBNO1OmSAG5ybxGBgKHS8CJi7wI4RWWwOJBJYQEokkpC3STlXa9ACyEGAAAtNHosNwqkgDPDmdofigpgt0HsqLR6MxFiCIhEAHSBuTaUzxKC-EApEjECMpLkU4oMTDiPYg-izeaZrIQexQCLq63DQwWB1krP54ToMuZtFyBj1bwgKDRTTBVyVm12kvBbTVm4g4QNEUQXt66RvTvFh3fMgR8IgzIZrPZ3MBoMhsMRhZ7As8LjTO4g+b9+aLo+ZivcPsLg2xY1mi0wsrjyHQoFkCdF+09mH8z+2qcfzCbdn1eXoMH+QEpjeD4hltCDZFhN4oUgJ8x2gGAkDgEdkLfF03Q9OhGBYBYOVTeZ+AjKAAHpqKyHJODhBEoHsTQfD5TwjFyYJViwkcB0WAiaCI70FmmUFykHBjMmLaAbnIvgaLohAWHQABlVYmCYZjTWAYA4kEWjTCMM0LBaf0tGqajDSMdQYiYbZgGolCIDUuyjAGaijC0hEmGo1gABYAA4ACYAE5z1oqAHOqCBzVzAADVoOiCSdvx0BKWNNeheOw7QcSgOAYmqGY813KAbnxDQaggFgEojBLIrohKACFCWJX40u7DKspykw8oKoqalvMAuodCJ7BM00Rvvc0GBSFpqtiuq2q1X5GqzCMBNdd1hK9Ejks6Mae35cT2ygQ7Uq-brHXktNVGq3R9EMExzHDZ1tqEz1iMWVaOqQY6dFOiTIGEP7tUB26FP4TV-s+3bvtExIIEh4HzuR1G7oo2QFAgeHCP2xYIn6kcoAAVSSbc0ckvMScdCmqaxxSyYJn6Meuh1z34ZH+UwvLcNQsnCHPYQ+Zw19BeF+ZhB21nRLeVA6agAA1bAlbZaGoGVOxHDllhla52BEBQVBVZV-4pczYQDelq9xHQ3Zg0GcUlk2EZ31KhYxjWDYth2N08W11UKokB2EDASBGHpLxfFQEEeD2n6qlqepGku7peiYWDhmTeYAUT70uidowXbdmFkymJcvd49ZNm2bg9gAWkDmwdaQPXZC9hTsfQLuRe4LuO7ULQnrtV7LFb1VLexppqhMjAu+wAAiVwl-5JeKRj4Al+Ifdzyzc6BYgVBjRDCBo6pBf9n+LvCGcffM03qlhFP0xz48Ler72G-9nv5cKv7kuf+h8JbH1fu-BkwAv4-zOH-f+5IP7PygOAi+sde7X07r-asx5bih1cMgkcb9UFQKtGyZQQddYFxYDIe6YttBHxhAJfA9R8A5DkC0YkqA6EMLCLCGQodCjqG8MGaAWgAJQGqHIDYys1IQGJEEOCNpDBEjeGGOOedEG+BYFQx22hnbeFdiAEYQCmIQGVuKRU9ErjVk8N4JgZiLEQCktY888pLEcjJDcSuNwK4RBBE-LRNJNHABYPGHkJRkxRmIOHSODBiHqOBAfeEDiFROKsdcc8tj7HmNSc4jJWY3FpI8SCHxIJiFMHEPfB26BarAHYGQNQwALDaCQC5VArh66SOkbI+RnwAb1GUd4VRVT8H4BzI05prS3wdzXP6YMoZBwQGHNoKJ70QBTATojFgfj5iBjmRuRZyzxCrKVioe6ZzbYRlAtwWpIVlBjPsBMlpbSOk7C6WYnpnRFEDJiEMzO98gA)

2023-09-12 15:57 UTC, andrewbranch commented
That’s... weird

2023-09-21 20:04 UTC, jfet97 commented
[Here](https://www.typescriptlang.org/play?ts=5.2.2#code/C4TwDgpgBAchDuAlCwCuAnAdgFXBAPNlBAB7ASYAmAzlABQB0TAhugObUBcUmEAbhHQBKKAF4AfFGaYQk0VCKlyVWnQBQUKEwasO3XgPRqREqAEtMAM0FREGqAH5b97tJABuNWtCQFEasBithAAxgD26JT4AegWbAA0UKiYANaYYfCY4l4+0ABiYWH4ACLEZBQ0fgFyUADe9gDaAArmmFApECBhllXAALoO3ABE8AAWzOSGQ2XKlaVOAIxQ3AAMagC+nt54CitByGhYuJD4JTMVtNj+wOJ0wNzFJpIFRcXi2ZoA9J9QAHoOOR22CW8jgSBQGBweFOpSUF16t3uUEeYmehRK73s3z+DiAA) is a 17 loc repro.

2023-09-22 17:09 UTC, andrewbranch commented
I think this is exposing an inference/assignability bug, not a logical consequence of switching the parameter type in the conditional extends type. I notice that if you swap `infer R` in `NewReturnType` for `any` or `unknown`, T1 starts taking the true branch of the conditional. So it seems like `infer R` is making the input type fail the `extends` assignability check, not `...args: never`. That will need to be fixed first or as part of this PR.

2023-09-24 15:28 UTC, jfet97 commented
@andrewbranch I'll tell you what I found out after some debugging of the code in [the playground](https://www.typescriptlang.org/play?ts=5.2.2#code/C4TwDgpgBAchDuAlCwCuAnAdgFXBAPNlBAB7ASYAmAzlABQB0TAhugObUBcUmEAbhHQBKKAF4AfFGaYQk0VCKlyVWnQBQUKEwasO3XgPRqREqAEtMAM0FREGqAH5b97tJABuNWtCQFEasBithAAxgD26JT4AegWbAA0UKiYANaYYfCY4l4+0ABiYWH4ACLEZBQ0fgFyUADe9gDaAArmmFApECBhllXAALoO3ABE8AAWzOSGQ2XKlaVOAIxQ3AAMagC+nt54CitByGhYuJD4JTMVtNj+wOJ0wNzFJpIFRcXi2ZoA9J9QAHoOOR22CW8jgSBQGBweFOpSUF16t3uUEeYmehRK73s3z+DiAA).

Inside `getConditionalType`, when we are applying the two versions of the conditional to `<D extends Record<string, unknown>>(t: D) => Foo<D>` we have:

1. With the classic definition of `ReturnType`: ![photo_2023-09-24_17-03-28](https://github.com/microsoft/TypeScript/assets/24520167/25b02202-33bc-4b3a-b51a-f16d9a6f6874)

1. With the modified defition, the one that uses `never` as the argument's type: 
![photo_2023-09-24_17-05-05](https://github.com/microsoft/TypeScript/assets/24520167/00f26806-a6bf-4e82-90c9-fcfcff900753)

In both cases `R` is correctly inferred as `Foo<Record<string, unknown>>`, but what is failing is the `isTypeAssignableTo` check between `checkType` and `inferredExtendsType`. What is that check for?

> Return falseType for a definitely false extends check. We check an instantiations of the two types with type parameters mapped to the wildcard type, the most permissive instantiations possible (the wildcard type is assignable to and from all types). If those are not related, then no instantiations will be and we can just return the false branch type.

This is exactly what happens, because the `never` version always returns what is present in the false branch in this specific playground.

So when `compareSignaturesRelated` comes into play because of `isTypeAssignableTo` we have:

1. `any` version:
1.1 `source` is `<D extends Record<string, unknown>>(t: D): Foo<D>`
1.2 `target` is `(...args: any): Foo<Record<string, unknown>>`
1.3 `source` becomes `(t: any): Foo<any>` because of `instantiateSignatureInContextOf`
1.4 So it seems all fine and dandy :)

2. `never` version:
2.1 `source` is `<D extends Record<string, unknown>>(t: D): Foo<D>`
2.2 `target` is `(...args: never): Foo<Record<string, unknown>>`
2.3 `source` becomes `(t: never): Foo<never>` because of `instantiateSignatureInContextOf`
2.4 When params are checked `sourceType = [t: never]` and `targetType = never` are compared, and this comparison seems to fail

2023-11-13 22:05 UTC, andrewbranch requested changes
Marking this as not currently mergeable based on my previous comment

2023-11-13 22:31 UTC, Andarist commented
I plan to get back to this soon-ish but I have a backlog of PR reviews to address right now so it will take some time 😉

2024-01-01 20:04 UTC, Andarist commented
@jakebailey @andrewbranch could you rerun test suite here? :)

2024-01-02 20:03 UTC, andrewbranch commented
@typescript-bot user test this
@typescript-bot test top200

2024-01-08 18:08 UTC, jfet97 commented
Hi @andrewbranch , do you think this change can become part of TS `5.4`? The assignability problem has been solved by changing the definitions again (arguments/return type are being inferred even when not needed, then discarded), and there are no more failed tests.

2024-01-08 21:39 UTC, andrewbranch commented
Why are the `infer _` needed?

2024-01-08 21:42 UTC, jfet97 commented
> Why are the `infer _` needed?

#56919 and [this comment](https://github.com/microsoft/TypeScript/pull/55714#issuecomment-1732597254) explain what happens if you don't use it.

2024-01-09 00:10 UTC, andrewbranch commented
@typescript-bot perf test

2025-07-30 21:42 UTC, sandersn commented
I'm trying to understand what state this PR is in. Here's my attempted summary:
- the original fix does indeed fix the bug with never-typed parameters causing ReturnType to produce `any`.
- but in one corner case, it hits another bug, #56919 
- necessitating an `infer _` workaround.

And we left off reviewing it at this point, without deciding whether `infer _` is an OK workaround, or whether this PR should wait until #56919 is fixed.

Is that accurate?

2025-07-30 21:51 UTC, jfet97 commented
> I'm trying to understand what state this PR is in. Here's my attempted summary:
> 
> - the original fix does indeed fix the bug with never-typed parameters causing ReturnType to produce `any`.
> 
> - but in one corner case, it hits another bug, #56919 
> 
> - necessitating an `infer _` workaround.
> 
> 
> 
> And we left off reviewing it at this point, without deciding whether `infer _` is an OK workaround, or whether this PR should wait until #56919 is fixed.
> 
> 
> 
> Is that accurate?

The infer trick was really promising, because with a concrete type it seemed to me that you can always come up with something that fails the extends check.

2025-11-06 07:36 UTC, Andarist commented
This is not a good approach given the type parameters might be invariant and if a type parameter of a generic signature gets instantiated with `never` then usually this breaks things. 

Fixing the original issue would, at the very least, require addressing https://github.com/microsoft/TypeScript/issues/62712

2025-11-06 07:36 UTC, closed without merging