Don't merge late bound assignment members with pre-existing symbols
microsoft/TypeScript pull request #60857
Opened 2024-12-26 10:37 UTC by Andarist

It seems to me those assignment members should always be ignored when explicit members are present (even late ones) and I took that approach. cc @weswigham @sandersn 

fixes https://github.com/microsoft/TypeScript/issues/60590

2024-12-26 10:38 UTC, Andarist commented on src/compiler/checker.ts
> +            symbol.valueDeclaration = member;
this isn't crucial for the fix but when investigating this issue I found those lines to be quite suspicious and there are no tests that would prove the old logic to be necessary

2024-12-26 10:57 UTC, Andarist commented on src/compiler/checker.ts
> +                }
I probably should look into allowing those from assignment declarations to merge together but tbf the behavior is not even overly consistent today:
```ts
const foo = 'foo'

class Test1 {
    constructor() {
        if (Math.random()) {
            this.prop = 12
        } else {
            this.prop = '' // ok
        }
    }
}

class Test2 {
    constructor() {
        if (Math.random()) {
            this[foo] = 12
        } else {
            this[foo] = '' // error
        }
    }
}
```

2024-12-26 10:57 UTC, Andarist commented on src/compiler/checker.ts
> +                    return links.resolvedSymbol = lateSymbol;
should this also use `getSymbolLinks(member.symbol).lateSymbol = symbol;`?

2025-01-06 20:21 UTC, DanielRosenwasser commented on src/compiler/checker.ts
> -            if (!symbol.valueDeclaration || symbol.valueDeclaration.kind !== member.kind) {
Was the original logic trying to preserve the somewhat-sketchy logic in the binder around which type of declaration "wins" out?

2025-01-06 20:21 UTC, DanielRosenwasser commented on src/compiler/checker.ts
> +            symbol.valueDeclaration = member;
```suggestion
        if (symbolFlags & SymbolFlags.Value) {
            symbol.valueDeclaration ??= member;
```

2025-01-06 23:18 UTC, sandersn requested changes

2025-01-06 23:18 UTC, sandersn commented on src/compiler/checker.ts
> -            if (!symbol.valueDeclaration || symbol.valueDeclaration.kind !== member.kind) {
It sure looks like it, but there's a separate utility function for that now: `setValueDeclaration`, which is more complicated*. Specifically, the `kind` check is *only* for namespaces there, which wouldn't apply to `this` property assignments.

I think the better fix to try is

```ts
if (symbolFlags & SymbolFlags.Value) {
  setValueDeclaration(symbol, member)
}
```

In other words, what the binder does in `addDeclarationToSymbol`.

*It also has a 3rd case for function property assignments in .d.ts files.

2025-01-07 10:42 UTC, Andarist commented on src/compiler/checker.ts
> -            if (!symbol.valueDeclaration || symbol.valueDeclaration.kind !== member.kind) {
I pushed out this change. Could you take another look?

2025-05-09 22:26 UTC, sandersn approved these changes
I noticed this after ignoring it for far too long. Would you mind merging from main before this goes in?

2025-05-10 08:48 UTC, Andarist commented
@sandersn done

2025-05-15 16:51 UTC, merged

2025-05-19 04:34 UTC, DingJun1028 reviewed
.